name: Update Age

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 18 12 10 *' # 00:00 on 13th October. (IST)

jobs:
  update_age:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          YOB=1995
          AGE=$(($(date -u +"%Y")-$YOB))
          
          sed -i -E "s;<\!-- Begin AGE -->[0-9]+<\!-- End AGE -->;<\!-- Begin AGE -->$AGE<\!-- End AGE -->;g" README.md
          
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git add README.md
          git commit -m "Update README.md"
          git push
